resolver: lts-3.13

# Local packages, usually specified by relative directory name
packages:
    - '.'
    - ext/ImplicitCAD

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
